- hosts: redmineserver

  roles:
    - system
    - pg
    - ruby
    - bundler
    - redmine
    - apache

  post_tasks:
    - name: 完了
      debug:
        msg='インストールが完了しました。 http://{{ ansible_default_ipv4.address }}/redmine/ にアクセスしてください。'
