- name: Redmineのソースコードをチェックアウト
  become: yes
  git:
    repo={{ redmine_git_url }}
    dest={{ redmine_dir }}
    version={{ redmine_version }}

- name: RedmineのURLおよびバージョンを表示
  debug:
    msg: 
      - "repo: {{ redmine_git_url }}"
      - "version: {{ redmine_version }}"

- name: database.ymlの作成
  become: yes
  template:
    src=database.yml
    dest={{ redmine_dir }}/config/database.yml
    force=no
  register:
    result_database_yml

- name: configuration.ymlの作成
  become: yes
  template:
    src=configuration.yml
    dest={{ redmine_dir }}/config/configuration.yml
    force=no

- name: Gemfile.lockが存在するか確認
  command:
    test -f {{ redmine_dir }}/Gemfile.lock
  register:
    result_test_gemfile
  failed_when: result_test_gemfile.rc not in [0, 1]
  changed_when: false

- name: bundle config path
  become: yes
  shell: "source ~/.bashrc&&bundle config set --local path 'vendor/bundle'"
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_test_gemfile.rc == 1

- name: bundle config without
  become: yes
  shell: "source ~/.bashrc&&bundle config set --local without 'development test'"
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_test_gemfile.rc == 1

- name: Gemfile.localを作成
  become: yes
  template:
    src=Gemfile.local
    dest={{ redmine_dir }}/Gemfile.local
    force=no

- name: bundle install
  become: yes
  shell: |
    source ~/.bashrc
    bundle install
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_test_gemfile.rc == 1
  register: bundle_install_result

- name: bundle update
  become: yes
  shell: |
    source ~/.bashrc
    bundle update
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_test_gemfile.rc == 0

- name: secret tokenの作成
  become: yes
  shell: |
    source ~/.bashrc
    bundle exec rake generate_secret_token
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: データベースのマイグレーション
  become: yes
  shell: |
    source ~/.bashrc
    bundle exec rake db:migrate
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production

- name: デフォルトデータ(日本語)をロード
  become: yes
  shell: |
    source ~/.bashrc
    bundle exec rake redmine:load_default_data
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
    RAILS_ENV: production
    REDMINE_LANG: ja
  when:
    result_database_yml is changed

- name: デフォルトの言語を日本語に変更
  become: yes
  shell: |
    source ~/.bashrc
    RAILS_ENV=production bundle exec rails r 'Setting["default_language"]="ja"'
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_database_yml is changed

- name: ユーザー名の表示形式を「姓 名」に変更
  become: yes
  shell: |
    source ~/.bashrc
    RAILS_ENV=production bundle exec rails r 'Setting["user_format"]=:lastname_firstname'
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_database_yml is changed

- name: 添付ファイルとリポジトリのエンコーディングを設定
  become: yes
  shell: |
    source ~/.bashrc
    RAILS_ENV=production bundle exec rails r 'Setting["repositories_encodings"]="UTF-8,CP932,EUC-JP"'
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_database_yml is changed

- name: 添付ファイルのサムネイルを表示
  become: yes
  shell: |
    source ~/.bashrc
    RAILS_ENV=production bundle exec rails r 'Setting["thumbnails_enabled"]="1"'
  args:
    chdir: "{{ redmine_dir }}"
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  when:
    result_database_yml is changed
