- name: Install Bundler
  gem:
    name: bundler
    state: present
    executable: /usr/local/rbenv/shims/gem

- name: Update Bundler to the latest version
  gem:
    name: bundler
    state: latest
    executable: /usr/local/rbenv/shims/gem

- name: Verify Bundler version
  shell: "source ~/.bashrc &&bundler --version"
  register: bundler_version

- name: Show Bundler version
  debug:
    msg: "Bundler version is {{ bundler_version.stdout }}"

- name: create gem_version by replacing the last digit of ruby_version with 0
  set_fact:
    gem_version: "{{ ruby_version | regex_replace('\\.[0-9]+$', '.0') }}"

